Config.Utils = {}

Config.ZoneNames = {
    AIRP = "Los Santos International Airport",
    ALAMO = "Alamo Sea",
    ALTA = "Alta",
    ARMYB = "Fort Zancudo",
    BANHAMC = "Banham Canyon Dr",
    BANNING = "Banning",
    BAYTRE = "Baytree Canyon", 
    BEACH = "Vespucci Beach",
    BHAMCA = "Banham Canyon",
    BRADP = "Braddock Pass",
    BRADT = "Braddock Tunnel",
    BURTON = "Burton",
    CALAFB = "Calafia Bridge",
    CANNY = "Raton Canyon",
    CCREAK = "Cassidy Creek",
    CHAMH = "Chamberlain Hills",
    CHIL = "Vinewood Hills",
    CHU = "Chumash",
    CMSW = "Chiliad Mountain State Wilderness",
    CYPRE = "Cypress Flats",
    DAVIS = "Davis",
    DELBE = "Del Perro Beach",
    DELPE = "Del Perro",
    DELSOL = "La Puerta",
    DESRT = "Grand Senora Desert",
    DOWNT = "Downtown",
    DTVINE = "Downtown Vinewood",
    EAST_V = "East Vinewood",
    EBURO = "El Burro Heights",
    ELGORL = "El Gordo Lighthouse",
    ELYSIAN = "Elysian Island",
    GALFISH = "Galilee",
    GALLI = "Galileo Park",
    golf = "GWC and Golfing Society",
    GRAPES = "Grapeseed",
    GREATC = "Great Chaparral",
    HARMO = "Harmony",
    HAWICK = "Hawick",
    HORS = "Vinewood Racetrack",
    HUMLAB = "Humane Labs and Research",
    JAIL = "Bolingbroke Penitentiary",
    KOREAT = "Little Seoul",
    LACT = "Land Act Reservoir",
    LAGO = "Lago Zancudo",
    LDAM = "Land Act Dam",
    LEGSQU = "Legion Square",
    LMESA = "La Mesa",
    LOSPUER = "La Puerta",
    MIRR = "Mirror Park",
    MORN = "Morningwood",
    MOVIE = "Richards Majestic",
    MTCHIL = "Mount Chiliad",
    MTGORDO = "Mount Gordo",
    MTJOSE = "Mount Josiah",
    MURRI = "Murrieta Heights",
    NCHU = "North Chumash",
    NOOSE = "N.O.O.S.E",
    OCEANA = "Pacific Ocean",
    PALCOV = "Paleto Cove",
    PALETO = "Paleto Bay",
    PALFOR = "Paleto Forest",
    PALHIGH = "Palomino Highlands",
    PALMPOW = "Palmer-Taylor Power Station",
    PBLUFF = "Pacific Bluffs",
    PBOX = "Pillbox Hill",
    PROCOB = "Procopio Beach",
    RANCHO = "Rancho",
    RGLEN = "Richman Glen",
    RICHM = "Richman",
    ROCKF = "Rockford Hills",
    RTRAK = "Redwood Lights Track",
    SanAnd = "San Andreas",
    SANCHIA = "San Chianski Mountain Range",
    SANDY = "Sandy Shores",
    SKID = "Mission Row",
    SLAB = "Stab City",
    STAD = "Maze Bank Arena",
    STRAW = "Strawberry",
    TATAMO = "Tataviam Mountains",
    TERMINA = "Terminal",
    TEXTI = "Textile City",
    TONGVAH = "Tongva Hills",
    TONGVAV = "Tongva Valley",
    VCANA = "Vespucci Canals",
    VESP = "Vespucci",
    VINE = "Vinewood",
    WINDF = "Ron Alternates Wind Farm",
    WVINE = "West Vinewood",
    ZANCUDO = "Zancudo River",
    ZP_ORT = "Port of South Los Santos",
    ZQ_UAR = "Davis Quartz"
}

Config.CarColours = {
    -- Black
    { Value = 0, Label = 'black'},
    { Value = 1, Label = 'black'},
    { Value = 2, Label = 'black'},
    { Value = 3, Label = 'grey'},
    { Value = 11, Label = 'black'},
    { Value = 12, Label = 'matte black'},
    { Value = 15, Label = 'black'},
    { Value = 16, Label = 'black'},
    { Value = 21, Label = 'oil'},
    { Value = 147, Label = 'carbon'},
     -- White
    { Value = 106, Label = 'white'},
    { Value = 107, Label = 'creme'},
    { Value = 111, Label = 'white'},
    { Value = 112, Label = 'white'},
    { Value = 113, Label = 'beige'},
    { Value = 121, Label = 'white'},
    { Value = 122, Label = 'white'},
    { Value = 131, Label = 'white'},
    { Value = 132, Label = 'white'},
    { Value = 134, Label = 'white'},
    -- Grey
    { Value = 4, Label = 'silver'},
    { Value = 5, Label = 'grey'},
    { Value = 6, Label = 'grey'},
    { Value = 7, Label = 'grey'},
    { Value = 8, Label = 'grey'},
    { Value = 9, Label = 'night'},
    { Value = 10, Label = 'aluminum'},
    { Value = 13, Label = 'grey'},
    { Value = 14, Label = 'grey'},
    { Value = 17, Label = 'grey'},
    { Value = 18, Label = 'grey'},
    { Value = 19, Label = 'silver'},
    { Value = 20, Label = 'grey'},
    { Value = 22, Label = 'grey'},
    { Value = 23, Label = 'grey'},
    { Value = 24, Label = 'grey'},
    { Value = 25, Label = 'silver'},
    { Value = 26, Label = 'titanium'},
    { Value = 66, Label = 'grey'},
    { Value = 93, Label = 'champagne'},
    { Value = 144, Label = 'grey'},
    { Value = 156, Label = 'grey'},
    -- Red
    { Value = 27, Label = 'red'},
    { Value = 28, Label = 'red'},
    { Value = 29, Label = 'red'},
    { Value = 30, Label = 'red'},
    { Value = 31, Label = 'red'},
    { Value = 32, Label = 'red'},
    { Value = 33, Label = 'red'},
    { Value = 34, Label = 'red'},
    { Value = 35, Label = 'red'},
    { Value = 39, Label = 'red'},
    { Value = 40, Label = 'red'},
    { Value = 43, Label = 'red'},
    { Value = 44, Label = 'red'},
    { Value = 46, Label = 'red'},
    { Value = 143, Label = 'red'},
    { Value = 150, Label = 'red'},
    -- Pink
    { Value = 135, Label = 'pink'},
    { Value = 136, Label = 'pink'},
    { Value = 137, Label = 'pink'},
    -- Blue
    { Value = 54, Label = 'blue'},
    { Value = 60, Label = 'blue'},
    { Value = 61, Label = 'blue'},
    { Value = 62, Label = 'blue'},
    { Value = 63, Label = 'blue'},
    { Value = 64, Label = 'blue'},
    { Value = 65, Label = 'blue'},
    { Value = 67, Label = 'blue'},
    { Value = 68, Label = 'blue'},
    { Value = 69, Label = 'blue'},
    { Value = 70, Label = 'blue'},
    { Value = 73, Label = 'blue'},
    { Value = 74, Label = 'blue'},
    { Value = 75, Label = 'blue'},
    { Value = 77, Label = 'blue'},
    { Value = 78, Label = 'blue'},
    { Value = 79, Label = 'blue'},
    { Value = 80, Label = 'blue'},
    { Value = 82, Label = 'blue'},
    { Value = 83, Label = 'blue'},
    { Value = 84, Label = 'blue'},
    { Value = 85, Label = 'blue'},
    { Value = 86, Label = 'blue'},
    { Value = 87, Label = 'blue'},
    { Value = 127, Label = 'blue'},
    { Value = 140, Label = 'blue'},
    { Value = 141, Label = 'blue'},
    { Value = 146, Label = 'blue'},
    { Value = 157, Label = 'blue'},
    -- Yellow
    { Value = 42, Label = 'yellow'},
    { Value = 88, Label = 'yellow'},
    { Value = 89, Label = 'yellow'},
    { Value = 91, Label = 'yellow'},
    { Value = 126, Label = 'yellow'},
    -- Green
    { Value = 49, Label = 'green'},
    { Value = 50, Label = 'green'},
    { Value = 51, Label = 'green'},
    { Value = 52, Label = 'green'},
    { Value = 53, Label = 'green'},
    { Value = 55, Label = 'green'},
    { Value = 56, Label = 'green'},
    { Value = 57, Label = 'green'},
    { Value = 58, Label = 'green'},
    { Value = 59, Label = 'green'},
    { Value = 92, Label = 'green'},
    { Value = 125, Label = 'green'},
    { Value = 128, Label = 'green'},
    { Value = 133, Label = 'green'},
    { Value = 151, Label = 'green'},
    { Value = 152, Label = 'green'},
    { Value = 155, Label = 'green'},
    -- Orange
    { Value = 36, Label = 'orange'},
    { Value = 38, Label = 'orange'},
    { Value = 41, Label = 'orange'},
    { Value = 123, Label = 'orange'},
    { Value = 124, Label = 'orange'},
    { Value = 130, Label = 'orange'},
    { Value = 138, Label = 'orange'},
    -- Brown
    { Value = 45, Label = 'copper'},
    { Value = 47, Label = 'brown'},
    { Value = 48, Label = 'brown'},
    { Value = 90, Label = 'bronze'},
    { Value = 94, Label = 'brown'},
    { Value = 95, Label = 'brown'},
    { Value = 96, Label = 'brown'},
    { Value = 97, Label = 'brown'},
    { Value = 98, Label = 'brown'},
    { Value = 99, Label = 'beige'},
    { Value = 100, Label = 'brown'},
    { Value = 101, Label = 'brown'},
    { Value = 102, Label = 'brown'},
    { Value = 103, Label = 'brown'},
    { Value = 104, Label = 'brown'},
    { Value = 105, Label = 'brown'},
    { Value = 108, Label = 'brown'},
    { Value = 109, Label = 'brown'},
    { Value = 110, Label = 'brown'},
    { Value = 114, Label = 'brown'},
    { Value = 115, Label = 'brown'},
    { Value = 116, Label = 'beige'},
    { Value = 129, Label = 'brown'},
    { Value = 153, Label = 'brown'},
    { Value = 154, Label = 'beige'},
    -- Purple
    { Value = 71, Label = 'purple'},
    { Value = 72, Label = 'purple'},
    { Value = 76, Label = 'violet'},
    { Value = 81, Label = 'purple'},
    { Value = 142, Label = 'violet'},
    { Value = 145, Label = 'purple'},
    { Value = 148, Label = 'purple'},
    { Value = 149, Label = 'purple'},
    -- Chrome
    { Value = 117, Label = 'chrome'},
    { Value = 118, Label = 'chrome'},
    { Value = 119, Label = 'aluminum'},
    -- Metal
    { Value = 120, Label = 'chrome'},
    { Value = 37, Label = 'gold'},
    { Value = 158, Label = 'gold'},
    { Value = 159, Label = 'gold'},
    { Value = 160, Label = 'gold'}
}